### ISSUE TITLE
Invalid pointer error

### ISSUE THREAD

**Issue by anshulvj** [cvlabbonn/tools_openni2#1]
Hi,
I installed tools_openni2 as given in instructions (running Ubuntu 14.04). Except qhull and ensenso it found everything else during cmake. However, when I connect my Asus Xtion and run `sudo ./viewer` it throws the following error:
`*** Error in `./viewer': realloc(): invalid pointer: 0x00007f446e0b0840 ***`

If I run `./viewer` without `sudo` it gives:
`*** Error in `./viewer': realloc(): invalid pointer: 0x00007f3c96c97840 ***
Aborted (core dumped)`

Any suggestions?

**Comment by api55** [comment]
Sorry for the late answer, 

Does it give you any other message? for example, "Initializing device and sensors" or "Sensors initialized" or "Initialization failed" or something similar? 
This is more or less to know where it gives you error. Also, does your camera works correctly with the default examples of OpenNI2?

**Comment by anshulvj** [comment]
Hi, Thanks for the reply, no worries.
I did not get any other error message except the one I mentioned. Asus xtion works with libfreenect2 and Kinect sdk on windows.

**Comment by api55** [comment]
I think it is something to do with the camera not initializing correctly. I think you should try the samples of openni to make sure it works correctly in linux. In some cases it is necessary to do some tweaking for it to work. if it is possible, compile it for debug and give the stacktrace, so I can help you identify your problem easily.

**Comment by anshulvj** [comment]
The Asus works with openni (and Openni2). I'll try the debug mode.

**Comment by samiksha-ambekar** [comment]
Hi Anshul,

Were you able to resolve this issue? I am facing the same issue on arm64 platform.

**Comment by anshulvj** [comment]
Closing the issue since not relevant anymore
